=== cidenw/the-pi-project-gadget-store/assets/xml/prod.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/prod" xmlns:tns="http://www.example.org/prod"
	elementFormDefault="qualified">

	<xs:element name="productList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="product" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="phone" />
										<xs:enumeration value="laptop" />
										<xs:enumeration value="accesories" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="brand" type="xs:string" />
							<xs:element name="productName" type="xs:string" />
							<xs:element name="price" type="xs:decimal" />
							<xs:element name="display" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="0" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="memory" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="0" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="storage" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="0" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="processor" type="xs:string" minOccurs="0"/>
							<xs:element name="camera" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="0" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="battery" type="xs:positiveInteger" minOccurs="0">
							</xs:element>

							<xs:element name="year">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="description" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="productID" type="xs:positiveInteger"
							use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>




</xs:schema>

=== cidenw/the-pi-project-gadget-store/assets/xml/2products.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:productList xmlns:tns="http://www.example.org/prod"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/prod prod.xsd ">
	<tns:product productID="1">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy On7</tns:productName>
		<tns:price>5799.00</tns:price>
		<tns:display>5.5</tns:display>
		<tns:memory>1.5</tns:memory>
		<tns:storage>8</tns:storage>
		<tns:processor>1.2GHz Qualcomm Snapdragon 410</tns:processor>
		<tns:camera>13</tns:camera>
		<tns:battery>3000</tns:battery>
		<tns:year>0</tns:year>
		<tns:description>
5.5-inch HD TFT display @ 720 x 1280 px, 267ppi
1.2GHz Qualcomm Snapdragon 410 processor Adreno 306
1.5GB RAM + 8GB ROM internal storage, Expandable via microSD, up to 256GB
13MP f/2.1 AF rear camera with LED Flash
5MP f/2.2 front camera
4G LTE Cat.4, Dual SIM, Dual Standby
Android 5.1.1 Lollipop
3000mAh Li-ion battery
</tns:description>
	</tns:product>
	<tns:product productID="2">
		<tns:type>phone</tns:type>
		<tns:brand>Asus</tns:brand>
		<tns:productName>Asus Zenfone Zoom</tns:productName>
		<tns:price>10999</tns:price>
		<tns:display>5.5</tns:display>
		<tns:memory>4</tns:memory>
		<tns:storage>128</tns:storage>
		<tns:processor>64-bit Intel Atom Z3590 Quad Core Processor</tns:processor>
		<tns:camera>13</tns:camera>
		<tns:battery>3000</tns:battery>
		<tns:year>0</tns:year>
		<tns:description>
Operating System: Android™ 5.0(With ASUS ZenUI)
Processor: 64-bit Intel Atom Z3590 Quad Core Processor (Running at 2.5GHz)
Display: 5.5-inch, Full HD 1920x1080/403 PPI,295ppi IPS
Internal Storage: 128GB eMCP Flash
Micro SD: MicroSD card (up to 128 GB)
Memory: 4GB LPDDR3 RAM
Battery: 3000 mAh Li-Polymer (non-removable)
SIM Cards: Micro-SIM
Network Standard: Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, hotspot, Bluetooth v4.0
Rear Camera: 13 Mega-Pixel
Front Camera: 5 Mega-Pixel
	</tns:description>
	</tns:product>
	<tns:product productID="3">
		<tns:type>laptop</tns:type>
		<tns:brand>Lenovo</tns:brand>
		<tns:productName>Lenovo IdeaPad 110-14IBR 14" Intel Celeron N3160 Quad Core 4GBBlack Windows 10  </tns:productName>
		<tns:price>14490</tns:price>
		<tns:display>14</tns:display>
		<tns:memory>4</tns:memory>
		<tns:storage>500</tns:storage>
		<tns:processor>Intel Celeron N3160 </tns:processor>
		<tns:camera>0.3</tns:camera>
		<tns:battery>24</tns:battery>
		<tns:year>2016</tns:year>
		<tns:description>
Operating System: Windows 10
Processor: Intel Celeron N3160 Processor 1.6GHz (2M Cache, up to 2.24GHz)
Quad Core
Display: 14" HD
Memory: 4GB DDR3
HDD: 500GB
SSD: n/a
VGA: INTEGRATED
ODD: Multi (tray in)
Battery: 3CELL 24WH
CAMERA 0.3M
Wifi: AC WIFI
		</tns:description>
	</tns:product>
	<tns:product productID="4">
		<tns:type>phone</tns:type>
		<tns:brand>Asus</tns:brand>
		<tns:productName>Asus Zenfone Max </tns:productName>
		<tns:price>6299</tns:price>
		<tns:display>5.5</tns:display>
		<tns:memory>2</tns:memory>
		<tns:storage>32</tns:storage>
		<tns:processor>Quad-core 1.2 GHz Cortex-A53</tns:processor>
		<tns:camera>13</tns:camera>
		<tns:battery>5000</tns:battery>
		<tns:year>2016</tns:year>
		<tns:description>
Android OS, v5.0.1 (Lollipop), upgradable to v6.0.1 (Marshmallow)
CPU Quad-core 1.2 GHz Cortex-A53
Protection: Corning Gorilla Glass 4
Touch: 10-finger capacitive Touch Screen with Anti-fingerprint technology
RAM: 2G LPDDR3
Storage: 32G EMMC
Asus Web Storage: 5 GB storage lifetime for free
Camera-Front: 5MP, f/2.0 Aperture, wide angle 85 degree Pano Selfie
Camera-Rear:13 MP, f/2.0 Aperture, l5 elements lens, autofocus, dual-LED (dual tone) flash
		</tns:description>
	</tns:product>
	<tns:product productID="5">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy S8+ 6.2</tns:productName>
		<tns:price>45990.0</tns:price>
		<tns:display>6.2</tns:display>
		<tns:memory>4.0</tns:memory>
		<tns:storage>64.0</tns:storage>
		<tns:processor>Qualcomm Snapdragon 835 processor</tns:processor>
		<tns:camera>12</tns:camera>
		<tns:battery>3500</tns:battery>
		<tns:year>2017</tns:year>
		<tns:description>
6.2" Quad HD sAMOLED
12MP OIS Dual Pixel (F.7) Main Camera
8MP AF (F1.7) Front Camera
4GB RAM + 64GB ROM expandable 
IP68-rated water and dust resistant
3,500mAh Battery
Android Nougat 7.0
LTE Hybrid Dual SIM
Fingerprint Scanner
Iris Scanner
Always On Display
Secure Folder
USB Type-C
		</tns:description>
	</tns:product>
	<tns:product productID="6">
		<tns:type>phone</tns:type>
		<tns:brand>Vivo</tns:brand>
		<tns:productName>Vivo V5 </tns:productName>
		<tns:price>12990</tns:price>
		<tns:display>5.5</tns:display>
		<tns:memory>3</tns:memory>
		<tns:storage>32</tns:storage>
		<tns:processor>Octa-core</tns:processor>
		<tns:camera>13</tns:camera>
		<tns:battery>3000</tns:battery>
		<tns:year>2016</tns:year>
		<tns:description>
Android OS, v6.0 (Marshmallow)
CPU:Octa-core
32 GB, 3 GB RAM
Camera:13 MP, f/2.2, autofocus, LED flash
Front Facing camera:16 MP, f/2.0, 1080p
		</tns:description>
	</tns:product>
	<tns:product productID="7">
		<tns:type>laptop</tns:type>
		<tns:brand>Dell</tns:brand>
		<tns:productName>Dell XPS 13 8GB Intel Core i5-5200U 13.3" Ultrabook</tns:productName>
		<tns:price>98740</tns:price>
		<tns:display>13.3</tns:display>
		<tns:memory>8</tns:memory>
		<tns:storage>256</tns:storage>
		<tns:processor> Intel Core i5-5200U 2.2GHz </tns:processor>
		<tns:battery>3000 </tns:battery>
		<tns:year>2015</tns:year>
		<tns:description>
Processor: Intel Core i5-5200U 2.2GHz Processor (3M Cache, up to 2.70GHz)
Storage: 256GB Solid State Drive
Memory: 8GB Dual Channel DDR3L-RS 1600Mhz (On Board)
Graphics: Intel HD Graphics 5500
Bluetooth: Bluetooth 4.0
Display:	13.3-inch FHD (1920 x 1080) infinity display
Battery: 52 WHr, 4-Cell Battery (integrated)OS: Windows 8.1
Disclaimer: Promo period Sep 18 - 30
Bluetooth Speaker may vary in color depending on availability
</tns:description>
	</tns:product>
	<tns:product productID="8">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy A7 (2017) Dual Sim (3GB, 32GB)</tns:productName>
		<tns:price>26990</tns:price>
		<tns:display>5.7</tns:display>
		<tns:memory>3</tns:memory>
		<tns:storage>32</tns:storage>
		<tns:processor>Exynos 7880 Octa</tns:processor>
		<tns:camera>16</tns:camera>
		<tns:battery>3600</tns:battery>
		<tns:year>2016</tns:year>
		<tns:description>
Android OS, v6.0.1 (Marshmallow)
5.7 inches Super AMOLED capacitive touchscreen, 16M colors
Exynos 7880 Octa
32 GB, 3 GB RAM, microSD, up to 256 GB (dedicated slot)
Dual SIM (Nano-SIM, dual stand-by)
16 MP, f/1.9, 27mm, autofocus, LED flash
Non-removable Li-Ion 3600 mAh battery
       </tns:description>
	</tns:product>
	
	<tns:product productID="9">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy S6 G9200 Dual Sim (3GB, 32GB) </tns:productName>
		<tns:price>19299</tns:price>
		<tns:display>5.1</tns:display>
		<tns:memory>3</tns:memory>
		<tns:storage>32</tns:storage>
		<tns:processor>1.5GHz octa-core</tns:processor>
		<tns:camera>16</tns:camera>
		<tns:battery>2550</tns:battery>
		<tns:year>2015</tns:year>
		<tns:description>
143.4 x 70.5 x 6.8 mm (5.65 x 2.78 x 0.27 in)
138 g (4.87 oz)
1440 x 2560 pixels (~577 ppi pixel density)
Android OS, v5.0.2 (Lollipop)
Quad-core 1.5 GHz Cortex-A53 and Quad-core 2.1 GHz Cortex-A57
32GB ROM, 3 GB RAM
16 MP, 2988 x 5312 pixels, optical image stabilization, autofocus, LED flash
		</tns:description>
	</tns:product>
	<tns:product productID="10">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy J7 Prime 32GB </tns:productName>
		<tns:price>12990</tns:price>
		<tns:display>5.5</tns:display>
		<tns:memory>3</tns:memory>
		<tns:storage>32</tns:storage>
		<tns:processor>Octa-Core 1.6GHz</tns:processor>
		<tns:camera>13</tns:camera>
		<tns:battery>3300</tns:battery>
		<tns:year>2016</tns:year>
		<tns:description>
Display: 5.5” Main Display 1080 x 1920 (FHD)
Processor: Octa-Core 1.6GHz
Memory: 3GB (RAM) + 32GB (ROM)
Expandable up to 256GB
Camera: 13MP (F1.9) + 8MP (F1.9)
OS: Android Marshmallow
Battery: 3,300 mAh
SIM Type: LTE Dual SIM Active (SIM 1 + SIM 2 + MicroSD), Nano-SIM (4FF)
Fingerprint sensor for added security
Ultra Data Saving (UDS)
Ultra Power Saving Mode (UPSM)
		</tns:description>
	</tns:product>
	<tns:product productID="11">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy A5 2016</tns:productName>
		<tns:price>15990</tns:price>
		<tns:display>5.2</tns:display>
		<tns:memory>2</tns:memory>
		<tns:storage>16</tns:storage>
		<tns:processor>Octa-core 1.6 GHz Cortex-A53</tns:processor>
		<tns:camera>13</tns:camera>
		<tns:battery>2900</tns:battery>
		<tns:year>2015</tns:year>
		<tns:description>
G LTE
5.2" FHD sAMOLED
13MP (OIS) / 5MP
		</tns:description>
	</tns:product>
	
	<tns:product productID="12">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy A5 (2017) Dual Sim (3GB, 32GB)</tns:productName>
		<tns:price>23990</tns:price>
		<tns:display>5.2</tns:display>
		<tns:memory>3</tns:memory>
		<tns:storage>32</tns:storage>
		<tns:processor>Octa-core 1.9 GHz Cortex-A53</tns:processor>
		<tns:camera>16</tns:camera>
		<tns:battery>3000</tns:battery>
		<tns:year>2016</tns:year>
		<tns:description>
Android OS, v6.0.1 (Marshmallow)
5.2 inches Super AMOLED capacitive touchscreen, 16M colors
Exynos 7880 Octa
Octa-core 1.9 GHz Cortex-A53
32 GB, 3 GB RAM, microSD, up to 256 GB (dedicated slot)
Dual SIM (Nano-SIM, dual stand-by)
16 MP, f/1.9, 27mm, autofocus, LED flash
Non-removable Li-Ion 3000 mAh battery
        </tns:description>
	</tns:product>
	
	<tns:product productID="13">
		<tns:type>phone</tns:type>
		<tns:brand>Samsung</tns:brand>
		<tns:productName>Samsung Galaxy A7(2016)</tns:productName>
		<tns:price>17959</tns:price>
		<tns:display>5.5</tns:display>
