=== cidenw/the-pi-project-gadget-store/assets/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/prod" xmlns:tns="http://www.example.org/prod"
	elementFormDefault="qualified">

	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firstName" type="xs:string" />
							<xs:element name="lastName" type="xs:string" />
							<xs:element name="email" type="xs:string" />
							<xs:element name="contact" type="xs:string" />
							<xs:element name="address" type="xs:string" />
							<xs:element name="city" type="xs:string" />
							<xs:element name="region" type="xs:string" />
							<xs:element name="password" type="xs:string" />
							<xs:element name="cart">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="product" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="productID"/>
													<xs:element name="quantity"/>	
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>




</xs:schema>

=== cidenw/the-pi-project-gadget-store/assets/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns="http://www.example.org/prod" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/prod users.xsd ">
<user><firstName>Waleed</firstName><lastName>Occidental</lastName><email>2l@gmail.com</email><contact>9062403450</contact><address>308 F. Torres</address><city>Alaminos City</city><region>ARMM</region><password>TmnDO/Lly70lpNY89yGHSVFNfexaKDt4GEsAqfBLJF07XNast2Dqf8XDD9xpbquHEL9eXJDJ6PPO8NvtllD3Uw==</password><cart><product><productID>1</productID><quantity>1</quantity></product></cart></user><user><firstName>Waleed</firstName><lastName>Occidental</lastName><email>waleed.occidental@gmail.com</email><contact>9062403450</contact><address>308 F. Torres</address><city>Alaminos City</city><region>ARMM</region><password>MDFJGIW6IERQbQvXCgVHRck5MQaU+cRFN9fLtJx2v233y5uMI5246MFwEayPV0ibO16I9SwFfGhj0lX2dSQtBw==</password></user></users>
